---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icecreamapp-ingress
spec:
  rules:
    - host: www.myicecreamapp.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: nodeapp-service 
                port:
                  number: {{ .Values.services.nodeapp.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icecreamapp-ingress
spec:
  rules:
    - host: www.myicecreamapp.com
      http:
        paths:
          - path: /v2
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service 
                port:
                  number: {{ .Values.services.mongoExpress.port }}

