apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.images.mongodb.repository }}:{{ .Values.images.mongodb.tag }}"
        ports:
        - containerPort: {{ .Values.services.mongodb.targetPort }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: username1
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: password1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  type: {{ .Values.services.mongodb.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.mongodb.port }}
      targetPort: {{ .Values.services.mongodb.targetPort }}
