apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-v2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"
