apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-secret
type: Opaque
data:
  username1: {{ .Values.mongodb.username | b64enc | quote }}
  password1: {{ .Values.mongodb.password | b64enc | quote }}