apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: "{{ .Values.images.nodeapp.repository }}:{{ .Values.images.nodeapp.tag }}"
        ports:
        - containerPort: {{ .Values.services.nodeapp.targetPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: username1
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: password1
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: {{ .Values.services.nodeapp.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.services.nodeapp.port }}
      nodePort: {{ .Values.services.nodeapp.nodePort }}
      targetPort: {{ .Values.services.nodeapp.targetPort }}