apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-canary
  labels:
    app: nodeapp
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
      track: canary
  template:
    metadata:
      labels:
        app: nodeapp
        track: canary
    spec:
      containers:
      - name: nodeapp
        image: zhuoran0219/ice-cream-management:1.1-canary
        ports:
        - containerPort: {{ .Values.services.nodeapp.targetPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: username1
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb-secret 
              key: password1
        - name: MONGO_URI
          value: "mongodb://admin:password@mongodb-service.{{ .Release.Namespace }}.svc.cluster.local:27017/ice-cream?authSource=admin"

