kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-egress-to-database
spec:
  podSelector:
    matchLabels:
      app: nodeapp
  policyTypes:
    - Egress
  egress:

    # Allow access to database
    - to:
        - podSelector:
            matchLabels:
              app: mongodb
