kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: developer
rules:
  - apiGroups: [""] # the core API group
    resources: ["pods", "services", "deployment", "replicaset", "namespaces"]
    verbs: ["get", "watch", "list", "create", "delete", "update"]
